default_provider = "age"

[providers.age]
type = "age"
recipients = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHac2M/WdCsejGpA87JlU2uwvVokPhqD7eufdMDoEU8z",
    "age1234vw9hka4p6eurluezk49kn46ywqpshywy6eypvs0kw0dep6a4sn6gyaz",
]

[secrets]
AUTOMATRON_ENV_GS_URI= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDU1NTU1QSBuUEs0cnFxTmowMWVGNFQ1WG41NUVIKzdoUHNodjFReW0wQW9LUFNIa2hNCnZEVFNWQ1FkYmhaaGR4cnhaNnBKQTFJcmlIblo3TWxlQTRKYTVyWHBRUjgKLT4gWDI1NTE5IHhYL3dOY0hUWWNwQzV1WTg5ejM2QUdKNTdUVVNUWVJEZlFlZk8wbU9GeWsKMS96TUdIWXpxbVJOOW5JQStRSnRWMHJJeEFYQmpmeXl5UnNFU0cvUmJrSQotLS0gWmErQlZXM1J3L2FCY1JTcHExZTVYWW1aN2xvV0FaT1FNTXZ1QXRvZWR5awoMoFXvpKR5HptiKYIwCNP1Nc2QygS/o6S1c3PY6V5kdAxAku0plOQMAef1PNR/ZZOUUdcAh8Eux38Yw+Cf6ARWPXSIewIt/csh" }
AGE_SECRET_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDU1NTU1QSBmTjZmKy9lMzVmZDdjanE2NGttZHVtMTR0VEVQVHRMVVRTYmNLWC9DTVZZCjd2NHo5ZU5wd251NCtNd0cvNTREa3VtaCs3eXA4R2VuOVdsSUhueE1LZUEKLT4gWDI1NTE5IERleis4WFB6K2lLRC8wdjlVdTkxTDlxa01wb1BkMjJtOWc1aTU4ajY0SGcKVlpMbkRNZlZKNXFYRW9IQlBzVXl0OGlUYndCdVJMbTBzYWdMNWRlQWtrdwotLS0ga1RNaDVlVm5zUXc3cFF4UTVCMDhqS3ZjTk13bnFtd0xWcmJNeGxOSHhKMArxpe14F0CnSZsC3ULOoT+Ux+4LCbzE91ocIW15MnN6S6ltSKz7R22qN5gp5THqgb5D4wWiwgAJly6Zbi4lRr7QEXHEztHfMxKZbteRIQyFzXhpE0cijc7r9tz8fl2ZOjbBJzwe2Pxbl7b/" }
